In [14]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Comparison ##

In [1]:
3 > 1

True

In [2]:
type(3 > 1)

bool

In [3]:
3 = 3

SyntaxError: can't assign to literal (<ipython-input-3-79bfd1be65e2>, line 1)

In [4]:
3 == 3

True

In [5]:
x = 5
y = 12

In [6]:
x == 7

False

In [7]:
y-x

7

In [8]:
4 < y-x <= 6

False

In [9]:
4 < y-x

True

In [10]:
y - x <= 6

False

In [11]:
True and False

False

In [12]:
True and True

True

In [15]:
# array comparisons
pets = make_array('dog', 'dog', 'cat', 'cat', 'rabbit')

In [16]:
pets == 'dog'

array([ True,  True, False, False, False])

In [17]:
1 + 1 + 0 + 0 + 0

2

In [18]:
sum(make_array(True,True,False,False,False))

2

In [19]:
sum(pets == 'dog')

2

In [20]:
# np.count_nonzero

sum(pets == 'dog')


2

In [22]:
np.count_nonzero(pets == "dog")

2

In [24]:
'dog' > 'cat'

True

In [26]:
'b' > 'a'

True

In [29]:
sum(pets > 'cat')

3

In [30]:
terms = Table().with_column('Semesters', np.arange(1, 9))
terms

Semesters
1
2
3
4
5
6
7
8

In [31]:
# predicates: are.above()
terms.where('Semesters',are.above(6))

Semesters
7
8

In [33]:
senior = are.above(6)
senior

In [34]:
senior(4)

False

In [35]:
# also_senior function
def also_senior(x):
    return x>6


In [36]:
also_senior(5)

False

In [37]:
terms.apply(also_senior,'Semesters')

array([False, False, False, False, False, False,  True,  True])

## Conditional Statements ##

In [40]:
def year_from_semesters(x):
    if x<= 0:
        return "invalid"
    elif x<= 2:
        return "Freshman"
    elif x<=4:
        return "Sophomore"
    elif x<=6:
        return "Junior"
    elif x<=8:
        return "Senior"
    
    

In [41]:
year_from_semesters(7)

'Senior'

In [43]:
year_from_semesters(700)

In [44]:
# add results to table as column

terms.with_column("Year",terms.apply(year_from_semesters,'Semesters'))



Semesters | Year
1         | Freshman
2         | Freshman
3         | Sophomore
4         | Sophomore
5         | Junior
6         | Junior
7         | Senior
8         | Senior

## Appending Arrays ##

In [45]:
first = np.arange(1, 6,)
second = np.arange(6, 11)

In [46]:
first

array([1, 2, 3, 4, 5])

In [47]:
# append a value to an array
np.append(first,300)

array([  1,   2,   3,   4,   5, 300])

In [49]:
first

array([1, 2, 3, 4, 5])

In [48]:
# append two arrays
np.append(first,second)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Random Selection ##

In [51]:
two_groups = ['treatment', 'control']

In [54]:
np.random.choice(two_groups,7)

array(['control', 'treatment', 'control', 'treatment', 'treatment',
       'treatment', 'control'], dtype='<U9')

In [55]:
sum(np.random.choice(two_groups,7)=="treatment")

1

In [58]:
sum(np.random.choice(two_groups,7)=="control")

5

In [59]:
outcomes = np.random.choice(two_groups,7)

In [60]:
outcomes

array(['control', 'control', 'control', 'treatment', 'control',
       'treatment', 'control'], dtype='<U9')

In [61]:
sum(outcomes == 'treatment')

2

In [62]:
sum(outcomes == 'control')

5

In [63]:
coin = ['heads', 'tails']

In [64]:
np.random.choice(coin)

'tails'

In [65]:
tosses = np.random.choice(coin,100)
tosses

array(['heads', 'heads', 'heads', 'heads', 'heads', 'heads', 'heads',
       'heads', 'heads', 'heads', 'tails', 'heads', 'heads', 'heads',
       'tails', 'heads', 'heads', 'heads', 'heads', 'heads', 'heads',
       'tails', 'heads', 'tails', 'tails', 'tails', 'heads', 'tails',
       'heads', 'tails', 'tails', 'heads', 'tails', 'tails', 'tails',
       'heads', 'tails', 'heads', 'tails', 'heads', 'heads', 'heads',
       'heads', 'heads', 'tails', 'tails', 'tails', 'tails', 'heads',
       'heads', 'tails', 'heads', 'heads', 'tails', 'tails', 'tails',
       'heads', 'heads', 'heads', 'heads', 'tails', 'tails', 'heads',
       'heads', 'tails', 'tails', 'tails', 'heads', 'tails', 'heads',
       'tails', 'tails', 'heads', 'heads', 'tails', 'heads', 'tails',
       'tails', 'heads', 'tails', 'heads', 'tails', 'tails', 'tails',
       'tails', 'heads', 'heads', 'heads', 'heads', 'heads', 'heads',
       'tails', 'heads', 'heads', 'heads', 'heads', 'tails', 'tails',
       'tails', 'tai

## For Statements ##

In [ ]:
Table().with_column(
    'Heads in 100 Tosses', outcomes
).hist(bins = np.arange(25.5, 75.5))